### ISSUE TITLE
Bug: Material @ assets/audio/newMsg.mp3 does not exist

### ISSUE THREAD

**Issue by kvii** [openimsdk/openim-h5-demo#1]
### What happened?

工程里缺了一个信息提示音的素材，打包的时候会报错。

https://github.com/openimsdk/openim-h5-demo/blob/35ea00744a514adbb6b28936cca0ac58e129e803/src/layout/useGlobalEvent.ts#L27

### What did you expect to happen?

把这个提示音的素材加上。

### How can we reproduce it (as minimally and precisely as possible)?

按照 README 中说明的方式进行打包，会报错 "Could not load xx/newMsg.mp3".

### Anything else we need to know?

我自己从网上随便找了个素材就能打包了。

### version

<details>
git 35ea00744a514adbb6b28936cca0ac58e129e803
</details>

### Cloud provider

<details>
无
</details>

### OS version

<details>
mac os Sonoma 14.0
</details>

### Install tools

<details>
无
</details>

**Comment by lgz5689** [comment]
fixed，please pull the latest code and try again
