### ISSUE TITLE
[BUG] Get sender status not updated after sending friend request

### ISSUE THREAD

**Issue by xiaohegg** [openimsdk/openim-h5-demo#12]
### OpenIM Server Version

3.5.3

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

在解除了好友关系后，然后在发送好友申请，接收方有收到好友申请同意的状态变化，但是发送方没有收到发送的状态变化，只有在浏览器无痕模式下才能获取到发送方的好友申请状态变化。

**Comment by lgz5689** [comment]
Try upgrading to the latest SDK

**Comment by xieshaoji01** [comment]
服务端版本不支持到最新的sdk ,版本3.5.3 在不调整服务端版本的情况下，升级到多少的sdk能够解决。同时又不影响其他功能呢？

**Comment by xieshaoji01** [comment]
> Try upgrading to the latest SDK

后端版本是v3.5  ，sdk 最高能升级到哪个版本。

**Comment by lgz5689** [comment]
It is recommended to keep the versions consistent, otherwise unexpected things may happen

**Comment by xieshaoji01** [comment]
> It is recommended to keep the versions consistent, otherwise unexpected things may happen

后端因为业务上有许多问题，当前只能保持在3.5版本。 请教一下sdk 最高能升级到多少版本呢？
