### ISSUE TITLE
能支持APICloud吗?

### ISSUE THREAD

**Issue by kangsange** [openimsdk/openim-h5-demo#4]
### Description

原来APICloud独立的时候，世界引用js文件就可以
现在被用友收购后改为avm模式了，avm文档：https://developer.yonyou.com/docs/avm/#/overview/index?index=0&subIndex=0
所有文档：https://developer.yonyou.com/docs/

请问openIM能兼容apicloud吗?

**Comment by kangsange** [comment]
?????

**Comment by lgz5689** [comment]
可以自己用demo尝试接入

**Comment by lgz5689** [comment]
All of the current client SDKS are based on [openim-sdk-core](https://github.com/openimsdk/openim-sdk-core) packaged files, you need to understand whether you can use native plugins in Android and IOS
