### ISSUE TITLE
Bug: 启动各种 报错

### ISSUE THREAD

**Issue by ericoudesu** [openimsdk/openim-h5-demo#5]
### What happened?

- 缺少 `rpc-shooter`
- 缺少 ` @jlongster/sql.js`
- 添加完 依赖 还是 报错: `[plugin:vite:import-analysis] Failed to resolve import "squel" from "src/utils/open-im-sdk-wasm/sqls/localStranger.js". Does the file exist?`

### What did you expect to happen?

不应该报错.

### How can we reproduce it (as minimally and precisely as possible)?

启动即报错.

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by lgz5689** [comment]
Pull the latest code and try again
