### ISSUE TITLE
[BUG] Each page refresh triggers all session changes

### ISSUE THREAD

**Issue by playWithMySelf** [openimsdk/openim-h5-demo#7]
### OpenIM Server Version

3.5

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

1、每次刷新页面都会请求所有会话，都会触发所有的会话变更
2、open-im-sdk-wasm换成3.5也一样出现

### Screenshots Link

<img width="1260" alt="微信图片_20240813100115" src="https://github.com/user-attachments/assets/e4b7ee15-6fa0-4c4f-9293-ce78a9cfd6e7">
<img width="525" alt="微信图片_20240813100122" src="https://github.com/user-attachments/assets/2d524307-5240-4f9d-a718-72bced068345">

**Comment by lgz5689** [comment]
use @openim/wasm-client-sdk@latest
